name: expense

networks:
  default:
    name: expense

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ExpenseApp@1
      MYSQL_DATABASE: transactions
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
  environment:
    DB_HOST: mysql
    DB_USER: root
    DB_PASSWORD: root
    DB_NAME: transactions
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:v1.0.0
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js"
    depends_on:
      mysql:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:v1.0.0
    container_name: frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "80:80"
